stages:
  - build
build:
  image: fedora:32
  stage: build
  script:
    - dnf install -y podman make
    - podman login -u="kkleine+llvm_ci_gilab_account" -p="${QUAY_IO_LLVM_CI_GITHUB_ACCOUNT_PASSWORD}" quay.io
    - make VERBOSE=1 fedora-32-image
    - make VERBOSE=1 push-fedora-32-image
  interruptible: true
  timeout: 30 minutes
