stages:
  - build
build:
  image: fedora:32
  stage: build
  script:
    - echo "Building container image"
    - >-
      docker login -u="kkleine+llvm_ci_gilab_account" -p="${QUAY_IO_LLVM_CI_GITHUB_ACCOUNT_PASSWORD}" quay.io
    - echo "Building container image"
    - make VERBOSE=1 fedora-32-image
    - echo "Pushing container image to quay.io"
    - make VERBOSE=1 push-fedora-32-image
  interruptible: true
  timeout: 30 minutes
