# Validate at https://gitlab.com/kwk/llvm-ci/-/ci/lint

build:
  stage: build
  image: docker:latest
  interruptible: true
  timeout: 30 minutes
  script:
    - docker login -u="kkleine+llvm_ci_gilab_account" -p="${QUAY_IO_LLVM_CI_GITHUB_ACCOUNT_PASSWORD}" quay.io
    - make VERBOSE=1 fedora-32-image
    - make VERBOSE=1 push-fedora-32-image
