stages:
  - Build docker image
build:
  image: ubuntu-20.04
  stage: Build and push container image
  script:
    - echo "Building container image"
    - >-
      docker login -u="kkleine+llvm_ci_github_account" -p="${{
      secrets.QUAY_IO_LLVM_CI_GITHUB_ACCOUNT_PASSWORD }}" quay.io
    - echo "Building container image"
    - make VERBOSE=1 fedora-32-image
    - echo "Pushing container image to quay.io"
    - make VERBOSE=1 push-fedora-32-image
  interruptible: true
  timeout: 30 minutes
