stages:
  - Build docker image
registry_login:
  stage: Build and push container image
  script:
    - echo "Building container image"
    - >-
      docker login -u="kkleine+llvm_ci_github_account" -p="${{
      secrets.QUAY_IO_LLVM_CI_GITHUB_ACCOUNT_PASSWORD }}" quay.io
  image: ubuntu-20.04
  interruptible: true
  timeout: 30 minutes
build_image:
  stage: Build docker image
  script:
    - echo "Building container image"
    - make VERBOSE=1 fedora-32-image
  interruptible: true
  timeout: 30 minutes
push_image_to_registry:
  stage: Build docker image
  script:
    - echo "Pushing container image to quay.io"
    - make VERBOSE=1 push-fedora-32-image
  interruptible: true
  timeout: 30 minutes
