version: "3.8"
services:

    # The buildbot master
    master:
        container_name: master-container
        # user: buildbot-master:root
        build:
            context: ./master
        ports:
            # Web-Frontend
            - "8010:8010"
            # Port to Try-Scheduler
            - "8031:8031"
            # Prometheus exporter (visit http://localhost:9101/metrics)
            - "9101:9101"
        # Only workers must reach the workers-port,
        # hence we only expose but not publish it on the host.
        expose:
            - "9989"
        volumes:
            - "./master/cfg:/home/buildbot-master/cfg:Z"
            - "./master/compose-secrets/:/master-secret-volume/:Z"
        environment:
            BUILDBOT_MASTER_TITLE: "Compose"
            BUILDBOT_MASTER_TRY_PORT: "8031"
            BUILDBOT_MASTER_PORT: "9989"
            BUILDBOT_WWW_PORT: "8010"
            BUILDBOT_WWW_URL: http://localhost:8010/
        networks:
            - master
            - worker
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8010"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
    
    # A buildbot worker
    worker1:
        container_name: worker-container
        build: ./worker
        environment:
            BUILDBOT_ACCESS_URI: localhost
            BUILDBOT_WORKER_NAME: Local Worker 1
            BUILDBOT_INFO_ADMIN: you@me.com
            BUILDBOT_MASTER: master:9989
        networks:
            - worker
        depends_on:
            - master
        volumes:
          - "./worker/compose-secrets:/buildbot-worker-secret-volume:Z"
    
    # Another buildbot worker
    worker2:
        container_name: worker-container
        build: ./worker
        environment:
            BUILDBOT_ACCESS_URI: localhost
            BUILDBOT_WORKER_NAME: Local Worker 2
            BUILDBOT_INFO_ADMIN: you@me.com
            BUILDBOT_MASTER: master:9989
        networks:
            - worker
        depends_on:
            - master
        volumes:
          - "./worker/compose-secrets:/buildbot-worker-secret-volume:Z"
    
    # Github self-hosted actions-runner
    runner:
        container_name: runner-container
        # TODO(kwk): Sadly I haven't figured out a way to get rid of this because the
        # github actions runner binary requires quite some permissions when it upgrades it self.
        # This self-upgrade cannot be stopped. 
        user: runner:root
        build: ./runner
        environment:
            GH_OWNER: ${GH_OWNER}
            GH_REPO: ${GH_REPO}
        networks:
            - master
        depends_on:
            - master
            - worker1
            - worker2
        volumes:
          - "./runner/compose-secrets:/runner-secret-volume:Z"

networks:
    master:
    worker: