apiVersion: v1
kind: Pod
metadata:
  name: llvm-ci-fedora32-x8664-pod
  labels:
    app: llvm-ci
    os: fedora
    os_version: "32"
    arch: x8664
    assertions: no
    ccache: yes
spec:
  containers:
    - name: llvm-ci-fedora32-x8664-container
      image: quay.io/kkleine/llvm-ci:fedora-32-x86_64-8961877
      resources:
        requests:
          memory: "16Gi"
        limits:
          memory: "16Gi"
      ports:
        - containerPort: 9090
      env:
        - name: LLVM_TARGETS_TO_BUILD
          value: "X86"
        - name: LLVM_ENABLE_ASSERTIONS
          value: Off
        - name: LLVM_CCACHE_BUILD
          value: "On"
        - name: BUILDKITE_AGENT_TOKEN
          valueFrom:
            secretKeyRef:
              name: buildkite-agent-token
              key: WebHookSecretKey