apiVersion: v1
kind: Pod
metadata:
  name: master-pod
  labels:
    os: "fedora"
    os_version: "33"
    arch: "x86_64"
    app: "buildbot"
    tier: "master"
    # Add your own key-value pairs
spec:
  containers:
    - name: master-container
      image: "${BUILDBOT_MASTER_IMAGE}"
      command: ["master.sh"]
      volumeMounts:
        - name: master-secret-volume
          mountPath: /master-secret-volume
          readOnly: true
      env:
        - name: BUILDBOT_WWW_URL
          value: "${BUILDBOT_WWW_URL}"
      ports:
        - containerPort: 8010
          name: www
        - containerPort: 9989
          name: workers
      livenessProbe:
        httpGet:
          path: /
          port: www
        initialDelaySeconds: 120
        periodSeconds: 10

  volumes:
    - name: master-secret-volume
      secret:
        secretName: master-secret