apiVersion: v1
kind: Service
metadata:
  name: master-service-www
  labels:
    app: buildbot
    tier: master
spec:
  selector:
    app: buildbot
    tier: master
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010
      name: www
---
apiVersion: v1
kind: Service
metadata:
  name: master-service-workers
  labels:
    app: buildbot
    tier: master
spec:
  selector:
    buildbot: master
  ports:
    - protocol: TCP
      port: 9989
      targetPort: 9989
      name: workers