apiVersion: v1
kind: Service
metadata:
  name: master-service-www
  labels:
    app: buildbot
    tier: master
spec:
  type: ClusterIP
  selector:
    app: buildbot
    tier: master
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010
      name: www
---
apiVersion: v1
kind: Service
metadata:
  name: master-workers-node-port
  labels:
    app: buildbot
    tier: master
spec:
  type: NodePort
  selector:
    app: buildbot
    tier: master
  ports:
    - protocol: TCP
      port: 9989
      targetPort: 9989
      name: workers
      # Noteports are typically above 30000, when assigned automatically
      nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: master-try-node-port
  labels:
    app: buildbot
    tier: master
spec:
  type: NodePort
  selector:
    app: buildbot
    tier: master
  ports:
    - protocol: TCP
      port: 8031
      targetPort: 8031
      name: try
      # Noteports are typically above 30000, when assigned automatically
      nodePort: 30008
      