name: Container Image CI

on:
  push:
    branches: [ master ]
  

jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make fedora-32-image
      run: make VERBOSE=1 fedora-32-image
