name: "Build and publish container images to quay.io"

on:
  push:
    branches: [ master ]
    paths:
    # Don't trigger a build if these files were modified
    # See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns-1
    - '!README.md'
    - '!yaml/**'
    - '!.dockerignore'

jobs:

  build-fedora-32-image:
    runs-on: ubuntu-20.04
    steps:
    - run: docker login -u="kkleine+llvm_ci_github_account" -p="${{ secrets.QUAY_IO_LLVM_CI_GITHUB_ACCOUNT_PASSWORD }}" quay.io
    - uses: actions/checkout@v2
    - name: make VERBOSE=1 fedora-32-image
      run: make VERBOSE=1 fedora-32-image

  build-fedora-rawhide-image:
    runs-on: ubuntu-20.04
    steps:
    - run: docker login -u="kkleine+llvm_ci_github_account" -p="${{ secrets.QUAY_IO_LLVM_CI_GITHUB_ACCOUNT_PASSWORD }}" quay.io
    - uses: actions/checkout@v2
    - name: make VERBOSE=1 fedora-rawhide-image
      run: make VERBOSE=1 fedora-rawhide-image
  
  build-centos-8-image:
    runs-on: ubuntu-20.04
    steps:
    - run: docker login -u="kkleine+llvm_ci_github_account" -p="${{ secrets.QUAY_IO_LLVM_CI_GITHUB_ACCOUNT_PASSWORD }}" quay.io
    - uses: actions/checkout@v2
    - name: make VERBOSE=1 centos-8-image
      run: make VERBOSE=1 centos-8-image
