name: Container Image CI

on:
  push:
    branches: [ master ]
  

jobs:

  build-fedora-32-image:
    runs-on: ubuntu-latest
    steps:
    - run: docker login -u="kkleine+llvm_ci_github_account" -p="${{ secrets.QUAY_IO_LLVM_CI_GITHUB_ACCOUNT_PASSWORD }}" quay.io
    - uses: actions/checkout@v2
    - name: make VERBOSE=1 fedora-32-image
      run: make VERBOSE=1 fedora-32-image
  build-centos-8-image:
    runs-on: ubuntu-latest
    steps:
    - run: docker login -u="kkleine+llvm_ci_github_account" -p="${{ secrets.QUAY_IO_LLVM_CI_GITHUB_ACCOUNT_PASSWORD }}" quay.io
    - uses: actions/checkout@v2
    - name: make VERBOSE=1 centos-8-image
      run: make VERBOSE=1 centos-8-image
